### ISSUE TITLE
Test code which was fixed in recent merges

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-server#7431]
To ensure it keeps working in the future:

- [ ] Order invoice and ticket PDF download https://github.com/fossasia/open-event-server/pull/7426
- [ ] Ticket deletion prevention https://github.com/fossasia/open-event-server/pull/7392
- [x] Direct ICS export https://github.com/fossasia/open-event-server/pull/7414
- [ ] Expand order access to ticket holders #7395
- [ ] Only prevent fulfilled or pending order users from deletion #7394
- [ ] Allow unverified users to buy free tickets #7393
- [x] Video Channels #7501

**Comment by Xx-Ashutosh-xX** [comment]
@iamareebjamal This would be my first issue & I think I would be able to do it, can you assign me to it.

**Comment by iamareebjamal** [comment]
We don't assign external contributors
. Please send a PR

**Comment by MohitPatni0731** [comment]
Can I work on this issue
